const nav=document.querySelector('.main-nav');const toggle=document.querySelector('.menu-toggle');toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});document.querySelectorAll('.main-nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle?.setAttribute('aria-expanded','false')}));
const modal=document.querySelector('#join-modal');const modalText=document.querySelector('#modal-text');document.querySelectorAll('[data-modal]').forEach(card=>card.addEventListener('click',e=>{e.preventDefault();const type=card.dataset.modal;modalText.textContent=type==='wechat'?'加入胖胖社区官方微信群，获取公告、组队和活动信息。':'加入胖胖社区抖音群，获取视频、直播和活动信息。';document.querySelector('#modal-qr').src=type==='wechat'?'assets/wechat-group.png':'assets/douyin-group.jpg';document.querySelector('#modal-qr').alt=type==='wechat'?'微信群二维码':'抖音群二维码';modal.hidden=false;document.body.style.overflow='hidden'}));document.querySelectorAll('[data-close]').forEach(el=>el.addEventListener('click',()=>{modal.hidden=true;document.body.style.overflow=''}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden){modal.hidden=true;document.body.style.overflow=''}});
const toast=document.querySelector('.toast');document.querySelector('.copy-btn')?.addEventListener('click',async e=>{const text=e.currentTarget.dataset.copy;try{await navigator.clipboard.writeText(text)}catch{}toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)});
// Motion-web inspired progressive reveal (kept dependency-free so the page works from a local HTML folder).
const revealItems=document.querySelectorAll('.section,.stat-card,.event-card,.community-card,.report-aside');
revealItems.forEach((el,index)=>{el.dataset.reveal='';el.style.transitionDelay=`${Math.min(index%4,3)*70}ms`});
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:.12});
revealItems.forEach(el=>revealObserver.observe(el));
const hero=document.querySelector('.hero');const heroBg=document.querySelector('.hero-bg');
if(hero && heroBg && !matchMedia('(prefers-reduced-motion: reduce)').matches){hero.addEventListener('pointermove',event=>{const r=hero.getBoundingClientRect();const x=(event.clientX-r.left)/r.width-.5;const y=(event.clientY-r.top)/r.height-.5;heroBg.style.transform=`scale(1.04) translate(${x*-8}px,${y*-5}px)`});hero.addEventListener('pointerleave',()=>heroBg.style.transform='')}
const recruitForm=document.querySelector('#recruit-form');
recruitForm?.addEventListener('submit',async e=>{e.preventDefault();const button=recruitForm.querySelector('button');button.disabled=true;button.textContent='提交中…';try{const response=await fetch('/api/submissions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(recruitForm))) });const result=await response.json();if(!response.ok)throw new Error(result.message);button.innerHTML='申请已记录 · 请添加 welink404';recruitForm.reset()}catch(error){button.textContent=error.message||'提交失败，请稍后重试';button.disabled=false}});
document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(button.dataset.copy)}catch{}toast?.classList.add('show');setTimeout(()=>toast?.classList.remove('show'),1800)}));


